### ISSUE TITLE
Convert DOC into reStructuredText

### ISSUE THREAD

**Issue by rakhimov** [open-psa/mef#1]
The automatic conversion may be lossy,
so manual editing is required to ensure correctness.

- [x] Separate chapters into files
- [x] Verify the equality

**Comment by rakhimov** [comment]
276621a - Fix the XML snippets

**Comment by mhibti** [comment]
Dear Olzhas,
If I understood I have to fix the rst documents.
If so, I will do as soon as possible.
Thanks,
Mohamed 

On 2016-12-08, Olzhas Rakhimov wrote:
> Assigned #1 to @mhibti.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 

Mohamed Hibti
Chercheur Expert 
EDF R&D - Département Management des Risques Industriels 
EDF Lab Saclay                                
7 boulevard Gaspard Monge, 91120 Palaiseau, France

mohamed.hibti@edf.fr                           
Tél. : +33 1 78 19 41 43                       

Un geste simple pour l'environnement, n'imprimez ce message que si vous en avez l'utilité.<br>

**Comment by rakhimov** [comment]
@mhibti No, there's nothing to worry. I am sorry for confusing you.
This assignment thing is pretty general, so other members know whom to refer.

**Comment by mhibti** [comment]
Ok thanks !
On 2016-12-08, notifications@github.com wrote:
> @mhibti No, there's nothing to worry. I am sorry for confusing you.
> This assignment thing is pretty general, so other members know whom to refer.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 

Mohamed Hibti
Chercheur Expert 
EDF R&D - Département Management des Risques Industriels 
EDF Lab Saclay                                
7 boulevard Gaspard Monge, 91120 Palaiseau, France

mohamed.hibti@edf.fr                           
Tél. : +33 1 78 19 41 43                       

Un geste simple pour l'environnement, n'imprimez ce message que si vous en avez l'utilité.<br>
